### ISSUE TITLE
Distributed table INSERTS

### ISSUE THREAD

**Issue by sundarv85** [Vertamedia/chproxy#39]
We have 3 clickhouse nodes (3 shards) in a cluster. It is noted in Readme for INSERTS that

```
..The routing logic may be embedded either directly into applications generating INSERTs or may be moved to a proxy. Proxy approach is better since it allows re-configuring ClickHouse cluster without modification of application configs and without application downtime. 
```

We are inserting in batches using `begin->prepare->(in loop exec)->commit`. So each individual commit will contain multiple rows which has to be distributed among shards. 

If we use distributed table, then the clickhouse shard will decide based on the sharding logic to decide to which shard this row has to go to. How will the proxy know to which shard should each row be written into? ie. how does the proxy know the sharding logic

Is it possible with chproxy and inserts to say that the 

1. chproxy just has to send each commit that it receives to one single clickhouse node which has a distributed table (which will do the re-routing as needed). 
2. chproxy has to round robin this among 3 different clickhouse nodes (for load balancing)
3. If a write fails, then it should retry the failure into the next clickhouse node

**Comment by valyala** [comment]
> How will the proxy know to which shard should each row be written into? ie. how does the proxy know the sharding logic?

the proxy routes incoming requests to a least loaded shard using round-robin selection if multiple shards exist with equal minimum load. This means that all the rows in the batch request will go to a single shard.

> chproxy just has to send each commit that it receives to one single clickhouse node which has a distributed table (which will do the re-routing as needed).

Just create the same distributed table on each node and insert into it via chproxy. Then chproxy will route each insert into least loaded node, which, in turn, will route individual rows to the appropriate shard.

> chproxy has to round robin this among 3 different clickhouse nodes (for load balancing)

It already does this. Round-robin is used for choosing a single node among multiple least loaded nodes.

> If a write fails, then it should retry the failure into the next clickhouse node

This isn't implemented, since it has many edge cases. For instance, clickhouse may insert a part of rows from the batch before failing. Then the same rows would be inserted into clickhouse on retry. So retry logic must be implemented on the client side, which has more information on the allowed edge cases and how to properly resolve them.

**Comment by sundarv85** [comment]
Thanks @valyala. I will check this.

**Comment by Yuhui0620** [comment]
> the proxy routes incoming requests to a least loaded shard using round-robin selection if multiple shards exist with equal minimum load.

I am confused about the meaning of "least loaded shard". Is it a shard with least connections?
