### ISSUE TITLE
chproxy con't proxy parameter to backgroud clickhouse server

### ISSUE THREAD

**Issue by johncai0** [Vertamedia/chproxy#62]
eg:
using "jdbc:clickhouse://172.0.0.3:8123/db?insert_deduplicate=0" connect to clickhouse server
the insert_deduplicate is works.

The front is chproxy, using "jdbc:clickhouse://172.0.0.3:9090/db?insert_deduplicate=0" connect to chproxy server, the insert_deduplicate is not works.

Is there a good solution?

**Comment by hagen1778** [comment]
Hi @johncai0 !
Proxy [removes all extra params](https://github.com/Vertamedia/chproxy#security) due to security reasons. You may either add required params to user configuration [here](https://github.com/Vertamedia/chproxy/tree/master/config#param_groups_config) so those params would be automatically added to every query, or update the source code [here](https://github.com/Vertamedia/chproxy/blob/master/scope.go#L292) and re-build proxy.

**Comment by johncai0** [comment]
Hi @hagen1778 
Thank you very much, it solved my problem perfectly.
It seems that I need to read the documentation carefully.
